# Generated by Django 5.1 on 2024-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
