# Generated by Django 5.1 on 2024-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(),
        ),
    ]
